apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICAiYXV0aCI6ICJhMkZzWVc1amFHRTZaMmh3WDJSMWFUSjRWRUozYldKcFdIRlVjR2xXWjFacFRWJAogICAgICAgICAgICAgICAgfQogICAgICAgIH0KfQo=
type: kubernetes.io/dockerconfigjson
