apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiYTJGc1lXNWphR0U2WjJod1gxQnVhVEpFVVVGT2RuRk5kV3RaVFhScVExUXlSbVpuVUVKcFNqUjBUelJRYXpod01nPT0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
